const test_input = ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."

import day_7

pub fn parse_manifold_test() {
  let state = day_7.count_splits(test_input)
  assert 21 == state.splits
}

pub fn concstruct_manifold_tree_test() {
  let tree = day_7.construct_manifold_tree(test_input)
  assert 40 == tree.permutations
}
